### ISSUE TITLE
1.6 issue

### ISSUE THREAD

**Issue by janat08** [peerlibrary/node-fiber-utils#3]
https://github.com/meteor/meteor/issues/9162
A bunch of things are wrong with that windows meteor install, so this is very much trash report.

**Comment by Steditor** [comment]
To make the report a bit more precise: In my case, executing a `npm install fiber-utils` does just fine - node-gyp seems to work well on my machine.
But: `meteor add peerlibrary:fiber-utils` fails in meteor 1.6 with the following log:

```
meteor add peerlibrary:fiber-utils
 => Errors while adding packages:

While loading package peerlibrary:fiber-utils@0.8.2:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild
--update-binary
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open
'C:\Users\...\AppData\Local\.meteor\packages\peerlibrary_fiber-utils\0.8.2\npm\node_modules\.temp-urfzcb.qa0a\node_modules\fibers\undefined'
gyp ERR! stack     at Object.fs.openSync (fs.js:648:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:553:33)
gyp ERR! stack     at readCAFile
(C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download
(C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at
C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:155:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\...\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\...\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--release"
gyp ERR! cwd C:\Users\...\AppData\Local\.meteor\packages\peerlibrary_fiber-utils\0.8.2\npm\node_modules\.temp-urfzcb.qa0a\node_modules\fibers
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
Der Befehl "nodejs" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
```

**Comment by Steditor** [comment]
It seems especially weird to me, that the script tries to access some `node_modules\fibers\undefined` path

**Comment by mitar** [comment]
So this is all a problem on Windows? Because on Mac things work great for me.

**Comment by mitar** [comment]
But it is strange because this package does not have any binary data.

I reopened the issue upstream in Meteor.

**Comment by mitar** [comment]
Closing here because there is nothing this package can do about it. :-(
